"""Cursor session source adapter.

Reads composer metadata from Cursor's workspace SQLite databases at:
~/Library/Application Support/Cursor/User/workspaceStorage/<hash>/state.vscdb

Each workspace has a key `composer.composerData` in the `ItemTable` with
JSON containing all composer sessions (name, mode, lines changed, dates).

Note: Cursor stores metadata but not full conversation text in the
easily-accessible SQLite. The `name` field is auto-generated by Cursor
and serves as a conversation summary.
"""

from __future__ import annotations

import json
import platform
import sqlite3
import sys
from datetime import date, datetime
from pathlib import Path

from .base import SessionContext, SessionMeta, SourceAdapter


def _get_cursor_workspace_dir() -> Path:
    """Return the Cursor workspace storage directory for the current platform."""
    system = platform.system()
    if system == "Darwin":
        return (
            Path.home()
            / "Library"
            / "Application Support"
            / "Cursor"
            / "User"
            / "workspaceStorage"
        )
    elif system == "Linux":
        return Path.home() / ".config" / "Cursor" / "User" / "workspaceStorage"
    elif system == "Windows":
        return (
            Path.home()
            / "AppData"
            / "Roaming"
            / "Cursor"
            / "User"
            / "workspaceStorage"
        )
    # Fallback to macOS
    return (
        Path.home()
        / "Library"
        / "Application Support"
        / "Cursor"
        / "User"
        / "workspaceStorage"
    )


CURSOR_WORKSPACE_DIR = _get_cursor_workspace_dir()


class CursorSource(SourceAdapter):
    name = "cursor"

    def discover_sessions(self, target_date: date) -> list[SessionMeta]:
        if not CURSOR_WORKSPACE_DIR.exists():
            return []

        sessions: list[SessionMeta] = []

        for ws_dir in CURSOR_WORKSPACE_DIR.iterdir():
            if not ws_dir.is_dir():
                continue

            db_file = ws_dir / "state.vscdb"
            if not db_file.exists():
                continue

            composers = self._read_composers(db_file, ws_dir.name, target_date)
            sessions.extend(composers)

        return sessions

    def extract_context(self, session: SessionMeta) -> SessionContext:
        # Cursor doesn't store full conversation text in accessible SQLite.
        # The auto-generated name and subtitle serve as the summary.
        name = session.title
        subtitle = session.extra.get("subtitle", "")

        excerpt_parts = [f"Composer: {name}"]
        if subtitle:
            excerpt_parts.append(f"Context: {subtitle}")

        mode = session.extra.get("mode", "")
        if mode:
            excerpt_parts.append(f"Mode: {mode}")

        if session.lines_added or session.lines_removed:
            excerpt_parts.append(
                f"Changes: +{session.lines_added} / -{session.lines_removed} lines"
            )

        files_count = session.extra.get("files_changed_count", 0)
        if files_count:
            excerpt_parts.append(f"Files changed: {files_count}")

        return SessionContext(
            meta=session,
            user_messages=[name],  # The name IS the summary
            assistant_responses=[],
            conversation_excerpt="\n".join(excerpt_parts),
        )

    def _read_composers(
        self, db_file: Path, ws_hash: str, target_date: date
    ) -> list[SessionMeta]:
        """Read composer data from a workspace's SQLite database."""
        sessions: list[SessionMeta] = []

        try:
            # Use immutable mode to avoid locking issues when Cursor is running
            import contextlib

            with contextlib.closing(
                sqlite3.connect(
                    f"file:{db_file}?mode=ro&immutable=1", uri=True
                )
            ) as conn:
                cur = conn.cursor()
                cur.execute(
                    "SELECT value FROM ItemTable "
                    "WHERE key = 'composer.composerData'"
                )
                row = cur.fetchone()

            if not row:
                return []

            data = json.loads(row[0])
            composers = data.get("allComposers", [])

            for composer in composers:
                if not self._is_on_date(composer, target_date):
                    continue

                meta = self._parse_composer(composer, ws_hash)
                sessions.append(meta)

        except sqlite3.OperationalError:
            # Database locked by Cursor — silently skip this workspace
            pass
        except (sqlite3.Error, json.JSONDecodeError, OSError) as e:
            print(f"[cursor] Warning: failed to read {db_file}: {e}",
                  file=sys.stderr)

        return sessions

    def _is_on_date(self, composer: dict, target_date: date) -> bool:
        """Check if composer was active on target date (timestamps are epoch ms)."""
        for field in ("lastUpdatedAt", "createdAt"):
            ts_ms = composer.get(field)
            if not ts_ms:
                continue
            try:
                dt = datetime.fromtimestamp(ts_ms / 1000)
                if dt.date() == target_date:
                    return True
            except (ValueError, TypeError, OSError):
                continue
        return False

    def _parse_composer(self, composer: dict, ws_hash: str) -> SessionMeta:
        """Parse a composer object into SessionMeta."""
        composer_id = composer.get("composerId", "")
        name = composer.get("name", "Untitled")
        mode = composer.get("unifiedMode", "unknown")

        created_ms = composer.get("createdAt", 0)
        updated_ms = composer.get("lastUpdatedAt", 0)

        created_at = ""
        updated_at = ""
        try:
            if created_ms:
                created_at = datetime.fromtimestamp(created_ms / 1000).isoformat()
            if updated_ms:
                updated_at = datetime.fromtimestamp(updated_ms / 1000).isoformat()
        except (ValueError, TypeError, OSError):
            pass

        return SessionMeta(
            session_id=composer_id,
            source="cursor",
            title=name,
            created_at=created_at,
            updated_at=updated_at,
            workspace=f"cursor-workspace:{ws_hash}",
            lines_added=composer.get("totalLinesAdded", 0),
            lines_removed=composer.get("totalLinesRemoved", 0),
            extra={
                "mode": mode,
                "subtitle": composer.get("subtitle", ""),
                "files_changed_count": composer.get("filesChangedCount", 0),
                "is_archived": composer.get("isArchived", False),
                "is_worktree": composer.get("isWorktree", False),
                "ws_hash": ws_hash,
            },
        )
